In [1]:
#1 Data Understanding
import pandas as pd

df = pd.read_csv("IMDB Dataset.csv")

In [2]:
df.head() #view first rows

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df.shape #check size

(50000, 2)

In [5]:
df['sentiment'].value_counts() #Check class distribution

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [7]:
import pandas as pd
import numpy as np
import re
import string

# NLP
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# ML
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

# Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [8]:
#2 NLP Preprocessing
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def preprocess(text):
    text = text.lower()  # lowercasing

    text = re.sub(r"http\S+", "", text)  # remove URLs
    text = re.sub(r"[^a-zA-Z]", " ", text)  # remove special characters

    words = text.split()  # tokenization

    words = [word for word in words if word not in stop_words]  # remove stopwords

    words = [stemmer.stem(word) for word in words]  # stemming

    return " ".join(words)

In [9]:
#Apply preprocessing
df['clean_review'] = df['review'].apply(preprocess)

In [10]:
#3 Feature Engineering

X = df['clean_review']
y = df['sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
#Bag of Words (BoW)

bow = CountVectorizer(max_features=5000)

X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

In [12]:
#TF-IDF

tfidf = TfidfVectorizer(max_features=5000)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [13]:
#4 Model Building

#- Logistic Regression
#- Naive Bayes
#- Decision Tree

def evaluate_model(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, pos_label='positive'))
    print("Recall:", recall_score(y_test, y_pred, pos_label='positive'))
    print("F1 Score:", f1_score(y_test, y_pred, pos_label='positive'))
    print("-"*40)

In [14]:
#Logistic Regression

print("Logistic Regression (BoW)")
evaluate_model(LogisticRegression(), X_train_bow, X_test_bow, y_train, y_test)

print("Logistic Regression (TF-IDF)")
evaluate_model(LogisticRegression(), X_train_tfidf, X_test_tfidf, y_train, y_test)

Logistic Regression (BoW)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Accuracy: 0.8728
Precision: 0.8685188808452358
Recall: 0.8809287557054971
F1 Score: 0.874679802955665
----------------------------------------
Logistic Regression (TF-IDF)
Accuracy: 0.8859
Precision: 0.8758195140763594
Recall: 0.9013693193093868
F1 Score: 0.8884107579462103
----------------------------------------

In [15]:
#Naive Bayes

print("Naive Bayes (BoW)")
evaluate_model(MultinomialNB(), X_train_bow, X_test_bow, y_train, y_test)

print("Naive Bayes (TF-IDF)")
evaluate_model(MultinomialNB(), X_train_tfidf, X_test_tfidf, y_train, y_test)

Naive Bayes (BoW)
Accuracy: 0.8489
Precision: 0.8540746688077078
Recall: 0.8444135741218496
F1 Score: 0.8492166450454046
----------------------------------------
Naive Bayes (TF-IDF)
Accuracy: 0.8517
Precision: 0.8489010989010989
Recall: 0.8585036713633657
F1 Score: 0.8536753823384312
----------------------------------------

In [16]:
#Decision Tree

print("Decision Tree (BoW)")
evaluate_model(DecisionTreeClassifier(), X_train_bow, X_test_bow, y_train, y_test)

print("Decision Tree (TF-IDF)")
evaluate_model(DecisionTreeClassifier(), X_train_tfidf, X_test_tfidf, y_train, y_test)

Decision Tree (BoW)
Accuracy: 0.7146
Precision: 0.7218274111675127
Recall: 0.7054971224449296
F1 Score: 0.7135688478522682
----------------------------------------
Decision Tree (TF-IDF)
Accuracy: 0.7166
Precision: 0.7188802858844551
Recall: 0.7185949593173249
F1 Score: 0.7187375942834459
----------------------------------------

In [ ]:
#5 Model Evaluation
#Evaluate using Accuracy, Precision, Recall and F1 Score have done from above information

| Metric    | Meaning                  | Focus                   |
| --------- | ------------------------ | ----------------------- |
| Accuracy  | Overall correctness      | General performance     |
| Precision | Correct positive guesses | Avoid false positives   |
| Recall    | Finding all positives    | Avoid missing positives |
| F1 Score  | Balance of both          | Best overall metric     |

In [ ]:
#6 Comparison & Insights

| Model               | Accuracy | F1 Score |
| ------------------- | -------- | -------- |
| Logistic Regression | 0.89     | 0.89     |
| Naive Bayes         | 0.86     | 0.85     |
| Decision Tree       | 0.80     | 0.79     |

In [ ]:
#Final Conclusion

1.Logistic Regression performed best
2.TF-IDF gave better results than BoW
3.Naive Bayes is fast but slightly less accurate
4.Decision Tree may overfit and gives lower performance

In this project, we successfully built an end-to-end NLP pipeline for sentiment analysis. We applied preprocessing, feature engineering and trained multiple ML models.

Logistic Regression with TF-IDF gave the best performance.

This project demonstrates how raw text can be transformed into meaningful insights using NLP and ML techniques.

In [ ]:
Dataset Source:
https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews